### ISSUE TITLE
About contribute to more demos

### ISSUE THREAD

**Issue by baishibona** [ros2/turtlebot2_demo#53]
I am not sure whether this is the place to ask, however we have a turtlebot autonomous mapping [repo](http://wiki.ros.org/turtlebot_exploration_3d) under ROS indigo for more than 8 months. I would like to transfer it to ROS2 to add to the demos for turtlebot. Any suggestions? Thanks!

**Comment by clalancette** [comment]
Having more demonstrations for ROS2 running on the turtlebot2 would be very welcome.  We have some notes about porting a ROS1 package over to ROS2 here: https://github.com/ros2/ros2/wiki/Migration-Guide .  If you run into trouble while doing the port, feel free to ask for advice on https://discourse.ros.org/c/ng-ros , and/or open up issues directly against particular repositories as you run into problems.  Good luck with the port, and let us know how it is going!  I'm going to close this particular issue out since this is a general question.
